version: "3"

services: 
    node:
        build:
            context: . 
            dockerfile: ./node.Dockerfile
        ports:
            - 8081:5000

    nginx:
        build:
            context: .
            dockerfile: ./nginx.Dockerfile
        ports:
            - 8080:80